package entities;
// Generated Apr 12, 2017 1:05:58 PM by Hibernate Tools 4.3.1

/**
 * Diemdanh generated by hbm2java
 */
public class DiemDanh implements java.io.Serializable {

    private Integer stt;
    private String tenMaMh;
    private String maSv;
    private boolean tuan1;
    private boolean tuan2;
    private boolean tuan3;
    private boolean tuan4;
    private boolean tuan5;
    private boolean tuan6;
    private boolean tuan7;
    private boolean tuan8;
    private boolean tuan9;
    private boolean tuan10;
    private boolean tuan11;
    private boolean tuan12;
    private boolean tuan13;
    private boolean tuan14;
    private boolean tuan15;

    public DiemDanh() {
        tuan1 = false;
        tuan2 = false;
        tuan3 = false;
        tuan4 = false;
        tuan5 = false;
        tuan6 = false;
        tuan7 = false;
        tuan8 = false;
        tuan9 = false;
        tuan10 = false;
        tuan11 = false;
        tuan12 = false;
        tuan13 = false;
        tuan14 = false;
        tuan15 = false;
    }

    public DiemDanh(String tenMaMh, String maSv, boolean tuan1, boolean tuan2, boolean tuan3, boolean tuan4, boolean tuan5, boolean tuan6, boolean tuan7, boolean tuan8, boolean tuan9, boolean tuan10, boolean tuan11, boolean tuan12, boolean tuan13, boolean tuan14, boolean tuan15, String diemdanhcol) {
        this.tenMaMh = tenMaMh;
        this.maSv = maSv;
        this.tuan1 = tuan1;
        this.tuan2 = tuan2;
        this.tuan3 = tuan3;
        this.tuan4 = tuan4;
        this.tuan5 = tuan5;
        this.tuan6 = tuan6;
        this.tuan7 = tuan7;
        this.tuan8 = tuan8;
        this.tuan9 = tuan9;
        this.tuan10 = tuan10;
        this.tuan11 = tuan11;
        this.tuan12 = tuan12;
        this.tuan13 = tuan13;
        this.tuan14 = tuan14;
        this.tuan15 = tuan15;
    }

    public Integer getStt() {
        return this.stt;
    }

    public void setStt(Integer stt) {
        this.stt = stt;
    }

    public String getTenMaMh() {
        return this.tenMaMh;
    }

    public void setTenMaMh(String tenMaMh) {
        this.tenMaMh = tenMaMh;
    }

    public String getMaSv() {
        return this.maSv;
    }

    public void setMaSv(String maSv) {
        this.maSv = maSv;
    }

    public boolean getTuan1() {
        return this.tuan1;
    }

    public void setTuan1(boolean tuan1) {
        this.tuan1 = tuan1;
    }

    public boolean getTuan2() {
        return this.tuan2;
    }

    public void setTuan2(boolean tuan2) {
        this.tuan2 = tuan2;
    }

    public boolean getTuan3() {
        return this.tuan3;
    }

    public void setTuan3(boolean tuan3) {
        this.tuan3 = tuan3;
    }

    public boolean getTuan4() {
        return this.tuan4;
    }

    public void setTuan4(boolean tuan4) {
        this.tuan4 = tuan4;
    }

    public boolean getTuan5() {
        return this.tuan5;
    }

    public void setTuan5(boolean tuan5) {
        this.tuan5 = tuan5;
    }

    public boolean getTuan6() {
        return this.tuan6;
    }

    public void setTuan6(boolean tuan6) {
        this.tuan6 = tuan6;
    }

    public boolean getTuan7() {
        return this.tuan7;
    }

    public void setTuan7(boolean tuan7) {
        this.tuan7 = tuan7;
    }

    public boolean getTuan8() {
        return this.tuan8;
    }

    public void setTuan8(boolean tuan8) {
        this.tuan8 = tuan8;
    }

    public boolean getTuan9() {
        return this.tuan9;
    }

    public void setTuan9(boolean tuan9) {
        this.tuan9 = tuan9;
    }

    public boolean getTuan10() {
        return this.tuan10;
    }

    public void setTuan10(boolean tuan10) {
        this.tuan10 = tuan10;
    }

    public boolean getTuan11() {
        return this.tuan11;
    }

    public void setTuan11(boolean tuan11) {
        this.tuan11 = tuan11;
    }

    public boolean getTuan12() {
        return this.tuan12;
    }

    public void setTuan12(boolean tuan12) {
        this.tuan12 = tuan12;
    }

    public boolean getTuan13() {
        return this.tuan13;
    }

    public void setTuan13(boolean tuan13) {
        this.tuan13 = tuan13;
    }

    public boolean getTuan14() {
        return this.tuan14;
    }

    public void setTuan14(boolean tuan14) {
        this.tuan14 = tuan14;
    }

    public boolean getTuan15() {
        return this.tuan15;
    }

    public void setTuan15(boolean tuan15) {
        this.tuan15 = tuan15;
    }

}
