package entities;
// Generated Apr 12, 2017 1:05:58 PM by Hibernate Tools 4.3.1



/**
 * Giaovu generated by hbm2java
 */
public class GiaoVu  implements java.io.Serializable {


     private String maGv;
     private String password;
     private String tenGv;

    public GiaoVu() {
    }

	
    public GiaoVu(String maGv, String password) {
        this.maGv = maGv;
        this.password = password;
    }
    public GiaoVu(String maGv, String password, String tenGv) {
       this.maGv = maGv;
       this.password = password;
       this.tenGv = tenGv;
    }
   
    public String getMaGv() {
        return this.maGv;
    }
    
    public void setMaGv(String maGv) {
        this.maGv = maGv;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTenGv() {
        return this.tenGv;
    }
    
    public void setTenGv(String tenGv) {
        this.tenGv = tenGv;
    }




}


