package entities;
// Generated Apr 12, 2017 1:05:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Monhoc generated by hbm2java
 */
public class MonHoc  implements java.io.Serializable {


     private String tenMaMh;
     private String tenMh;
     private Date ngayBd;
     private Date ngayKt;
     private String gioBd;
     private String gioKt;
     private String tenPh;
     private String thu;

    public MonHoc() {
    }

	
    public MonHoc(String tenMaMh, String tenMh, Date ngayBd, Date ngayKt, String gioBd, String gioKt) {
        this.tenMaMh = tenMaMh;
        this.tenMh = tenMh;
        this.ngayBd = ngayBd;
        this.ngayKt = ngayKt;
        this.gioBd = gioBd;
        this.gioKt = gioKt;
    }
    public MonHoc(String tenMaMh, String tenMh, Date ngayBd, Date ngayKt, String gioBd, String gioKt, String tenPh, String thu) {
       this.tenMaMh = tenMaMh;
       this.tenMh = tenMh;
       this.ngayBd = ngayBd;
       this.ngayKt = ngayKt;
       this.gioBd = gioBd;
       this.gioKt = gioKt;
       this.tenPh = tenPh;
       this.thu = thu;
    }
   
    public String getTenMaMh() {
        return this.tenMaMh;
    }
    
    public void setTenMaMh(String tenMaMh) {
        this.tenMaMh = tenMaMh;
    }
    public String getTenMh() {
        return this.tenMh;
    }
    
    public void setTenMh(String tenMh) {
        this.tenMh = tenMh;
    }
    public Date getNgayBd() {
        return this.ngayBd;
    }
    
    public void setNgayBd(Date ngayBd) {
        this.ngayBd = ngayBd;
    }
    public Date getNgayKt() {
        return this.ngayKt;
    }
    
    public void setNgayKt(Date ngayKt) {
        this.ngayKt = ngayKt;
    }
    public String getGioBd() {
        return this.gioBd;
    }
    
    public void setGioBd(String gioBd) {
        this.gioBd = gioBd;
    }
    public String getGioKt() {
        return this.gioKt;
    }
    
    public void setGioKt(String gioKt) {
        this.gioKt = gioKt;
    }
    public String getTenPh() {
        return this.tenPh;
    }
    
    public void setTenPh(String tenPh) {
        this.tenPh = tenPh;
    }
    public String getThu() {
        return this.thu;
    }
    
    public void setThu(String thu) {
        this.thu = thu;
    }




}


