package entities;
// Generated Apr 12, 2017 1:05:58 PM by Hibernate Tools 4.3.1



/**
 * Sinhvien generated by hbm2java
 */
public class SinhVien  implements java.io.Serializable {


     private String maSv;
     private String password;
     private String tenSv;

    public SinhVien() {
    }

	
    public SinhVien(String maSv, String password) {
        this.maSv = maSv;
        this.password = password;
    }
    public SinhVien(String maSv, String password, String tenSv) {
       this.maSv = maSv;
       this.password = password;
       this.tenSv = tenSv;
    }
   
    public String getMaSv() {
        return this.maSv;
    }
    
    public void setMaSv(String maSv) {
        this.maSv = maSv;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTenSv() {
        return this.tenSv;
    }
    
    public void setTenSv(String tenSv) {
        this.tenSv = tenSv;
    }




}


